- .changeset/proud-socks-punch.md
- package.json
- chore(package.json): edit description
> chore(package.json): edit description

- .changeset/lemon-kings-jam.md
- README.md
- Docs(readme): add title section
> docs(README): add title section

- .changeset/stupid-flowers-prove.md
- package.json
> fix: empty package

- .changeset/six-adults-divide.md
- README.md
> docs(README): adjust layout

- .changeset/bright-coats-sleep.md
- package.json
- chore(package.json): adjust description and command
> chore(package.json): adjust description and command

- .changeset/moody-knives-dream.md
- examples/src/BasicForm/Controller.tsx
- examples/src/BasicForm/index.tsx
- src/index.ts
- Fix(useForm): correct dynamic field value
> Fix(useForm): correct dynamic field value

- .changeset/new-ants-brush.md
- src/index.ts
- fix(useForm): eliminate useLayoutEffect warning in SSR
> fix(useForm): eliminate useLayoutEffect warning in SSR

- .changeset/cool-impalas-serve.md
- README.md
- docs(readme): add milestone section
> docs(readme): add milestone section

- .changeset/healthy-geese-guess.md
- examples/src/BasicForm/index.tsx
- src/index.ts
- src/types/index.ts
- src/types/react-cool-form.d.ts
- feat(useForm): accept function as the values argv of the reset method
> feat(useForm): accept function as the values argv of the reset method

- .changeset/unlucky-badgers-exist.md
- package.json
- rollup/config.js
- rollup/createConfig.js
> feat: support UMD format

- .changeset/cool-feet-decide.md
- examples/src/BasicForm/index.tsx
- package.json
- rollup/createConfig.js
- src/index.ts
- src/types/react-cool-form.d.ts
- refactor(useForm): adjust export format
> refactor(useForm): adjust export format

- .changeset/beige-geckos-draw.md
- README.md
> Feat: some feature

- .changeset/ninety-coats-fry.md
- .github/workflows/check-and-test.yml
- ci: adjust the check-and-test action
> ci: adjust the check-and-test action

- .changeset/late-days-compete.md
- package.json
- yarn.lock
> upgrade: react v16 to v17

- .changeset/five-phones-grab.md
- examples/src/BasicForm/index.tsx
- src/useForm.ts
- perf(useForm): remove `setFieldTouchedIfNeeded()` to reduce bundle size
> perf(useForm): remove setFieldTouchedIfNeeded() to reduce bundle size

- .changeset/young-ghosts-carry.md
- examples/src/BasicForm/index.tsx
- src/useForm.ts
- perf(useForm): reduce bundle size by simplify code
> perf(useForm): reduce bundle size by simplify code

- .changeset/silly-bobcats-remember.md
- examples/src/BasicForm/Controller.tsx
- examples/src/BasicForm/index.tsx
- src/useForm.ts
- feat(useForm): support built-in validation
> feat(useForm): support built-in validation

- .changeset/cyan-seahorses-love.md
- examples/src/BasicForm/index.tsx
- src/useForm.ts
- refactor(useForm): remove un-necessary for loop from Mutation Observer
> refactor(useForm): remove un-necessary for loop from Mutation Observer

- .changeset/tasty-colts-watch.md
- examples/src/BasicForm/index.tsx
- src/useForm.ts
- src/utils.ts
- feat: use unset for clear error
> feat: use unset for clear error

- .changeset/fair-monkeys-arrive.md
- examples/src/BasicForm/index.tsx
- src/index.ts
- src/types/index.ts
- src/types/react-cool-form.d.ts
- src/useForm.ts
- src/utils.ts
- feat: expose `get()` and `set()` utility functions
> feat: expose get() and set() utility functions

- .changeset/lemon-lies-itch.md
- examples/src/BasicForm/index.tsx
- src/types/index.ts
- src/useForm.ts
- src/useState.ts
- Perf: avoid un-necessary re-render
- Refactor: strip hidden input from element checking
> avoid un-necessary re-render & strip hidden input from element checking

- .changeset/sour-rabbits-behave.md
- .eslintrc.js
- examples/src/BasicForm/Controller.tsx
- examples/src/BasicForm/index.tsx
- src/types/index.ts
- src/types/react-cool-form.d.ts
- src/useForm.ts
- src/useState.ts
- src/utils.ts
- Feat(useForm): set state via the `defaultValue` prop
> Feat(useForm): set state via the defaultValue prop

- .changeset/ten-fireants-do.md
- examples/src/BasicForm/index.tsx
- src/useForm.ts
- Refactor(useForm): check ignored fields in the `getFields()`
> refactor(useForm): move ignoreFieldsRef to getFields()

- .changeset/tame-forks-film.md
- .eslintrc.js
- examples/src/BasicForm/index.tsx
- src/useForm.ts
- src/utils.ts
- fix(useForm): correct number data type
> fix(useForm): correct number data type

- .changeset/thick-seahorses-kiss.md
- examples/package.json
- examples/src/BasicForm/index.tsx
- package.json
- src/useForm.ts
- Feat(useForm): auto add/remove fields
> Feat(useForm): auto add/remove fields

- .changeset/silent-cameras-shake.md
- examples/src/BasicForm/index.tsx
- src/useForm.ts
- fix(useForm): correct dynamic fields behavior
> fix(useForm): correct dynamic fields behavior

- .changeset/slow-books-exercise.md
- src/useForm.ts
- fix(useForm): correct the logic of avoid double validating of setFieldTouched()
> fix(useForm): correct the logic of avoid double validating of setFieldTouched()

- .changeset/odd-jokes-wink.md
- src/useForm.ts
- Refactor(useForm): remove `setFieldTouchedMaybeValidate()`
> refactor(useForm): remove setFieldTouchedMaybeValidate()

- .changeset/shaggy-yaks-look.md
- examples/src/BasicForm/index.tsx
- src/useForm.ts
- Fix(useForm): cache the previous built-in errors for better DX
> fix(useForm): cache previous built-in errors for better DX

- .changeset/clean-phones-wink.md
- examples/src/BasicForm/index.tsx
- src/types/index.ts
- src/types/react-cool-form.d.ts
- src/useForm.ts
- src/useState.ts
- Refactor(useForm): change the `ignoreFields` config to `iControlledFields`
> refactor(useForm): change the ignoreFields to iControlledFields

- .changeset/rotten-candles-divide.md
- src/useForm.ts
- src/useState.ts
- src/utils.ts
- Feat(useForm): set all fields to touched when submitting
> feat(useForm): set all fields to touched when submitting

- .changeset/tough-swans-prove.md
- examples/src/BasicForm/index.tsx
- src/types/index.ts
- src/types/react-cool-form.d.ts
- src/useForm.ts
- Refactor(useForm): change `iControlledFields` config to `iControlFields`
> refactor(useForm): change iControlledFields config to iControlFields

- .changeset/slow-cameras-deliver.md
- examples/src/BasicForm/Controller.tsx
- examples/src/BasicForm/index.tsx
- src/types/index.ts
- src/types/react-cool-form.d.ts
- src/useForm.ts
- Feat(useForm): add `excludeFields` config
> feat(useForm): add excludeFields config

- .changeset/wet-cheetahs-return.md
- src/useState.ts
- Fix(useState): debug event not be sent correctly
> fix(useState): debug event not be sent correctly

- .changeset/stale-clocks-exercise.md
- examples/src/BasicForm/index.tsx
- src/useForm.ts
- Refactor(useForm): use validate-field instead of validate-form for single updated field
> Refactor(useForm): use validate-field instead of validate-form for single updated field

- .changeset/forty-trees-type.md
- examples/src/BasicForm/Controller.tsx
- examples/src/BasicForm/index.tsx
- src/useForm.ts
- Fix(useForm): correct the logic between controlled and un-controlled fields
> Fix(useForm): correct the logic between controlled and un-controlled fields

- .changeset/popular-bags-suffer.md
- src/useForm.ts
- Fix(useForm): get the deep initial value as the default value of field
> fix(useForm): get the deep initial value as the default value of field

- .changeset/twenty-monkeys-behave.md
- src/types/index.ts
- src/types/react-cool-form.d.ts
- src/useForm.ts
- Refactor(useForm): consist options name of the `setFieldValue` method
> refactor(useForm): consist options name of the setFieldValue method

- .changeset/long-horses-wash.md
- src/useForm.ts
- Fix(useForm): avoid duplicated set field touched for `controller`
> Fix(useForm): avoid duplicated set field touched for controller

- .changeset/moody-phones-destroy.md
- .gitignore
- examples/package.json
- examples/src/BasicForm/index.tsx
- examples/yarn.lock
- package.json
- src/types/index.ts
- src/types/react-cool-form.d.ts
- src/useForm.ts
- yarn.lock
- Refactor(useForm): remove the `iControlFields` and `excludeFields` configs, use new `ignoreFields` instead
> Refactor(useForm): remove the "iControlFields" and "excludeFields" configs, use new "ignoreFields" instead

- .changeset/mean-spoons-sing.md
- examples/src/BasicForm/Controller.tsx
- src/types/index.ts
- src/types/react-cool-form.d.ts
- src/useForm.ts
- Refactor(useForm): change the `parser` option of controller to `parse`
> Refactor(useForm): change the "parser" option of controller to "parse"

- .changeset/chilled-beds-share.md
- examples/src/BasicForm/Controller.tsx
- examples/src/BasicForm/index.tsx
- src/types/index.ts
- src/types/react-cool-form.d.ts
- src/useForm.ts
- Feat(useForm): add `format` option for `controller`
> Feat(useForm): add "format" option for "controller"

- .changeset/famous-rice-know.md
- .changeset/long-dolphins-jog.md
- bundlesize.config.json
- examples/src/BasicForm/index.tsx
- src/types/index.ts
- src/types/react-cool-form.d.ts
- src/useForm.ts
- src/utils.ts
- Feat(useForm): get touched error only
> Feat(useForm): get touched error only

- .changeset/tough-poets-sneeze.md
- examples/src/BasicForm/index.tsx
- src/types/index.ts
- src/types/react-cool-form.d.ts
- src/useForm.ts
- Refactor(useForm): adjust the `watch` arg of `getState()`
> Refactor(useForm): adjust the "watch" arg of "getState()"

- .changeset/famous-beers-kick.md
- .changeset/quiet-olives-bathe.md
- bundlesize.config.json
- examples/src/BasicForm/index.tsx
- src/types/index.ts
- src/useForm.ts
- src/useState.ts
- src/utils.ts
- Fix(useForm): correct the logic of `dirtyFields` and `isDirty`
> Fix(useForm): correct the logic of "dirtyFields" and "isDirty"

- .changeset/serious-comics-allow.md
- src/useForm.ts
- Refactor(useForm): re-use methods
> Refactor(useForm): re-use methods

- .changeset/nervous-goats-talk.md
- README.md
- examples/src/BasicForm/index.tsx
- src/types/index.ts
- src/types/react-cool-form.d.ts
- src/useForm.ts
- Feat(useForm): adjust the API of `getState()`
> Feat(useForm): adjust the API of "getState()"

- .changeset/neat-mugs-search.md
- examples/src/BasicForm/index.tsx
- src/useForm.ts
- Fix(useForm): correct the behavior of built-in validation
> Fix(useForm): correct the behavior of built-in validation

- .changeset/little-lobsters-obey.md
- src/hooks/useState.ts
- src/types/index.ts
- src/useForm.ts
- Refactor(useState): remove `setDefaultValuesRef` method
> Refactor(useState): remove "setDefaultValuesRef" method

- .changeset/afraid-hornets-switch.md
- src/index.ts
- src/types/react-cool-form.d.ts
- Feat: expose the `unset` utility function
> Feat: expose the "unset" utility function

- .changeset/lemon-rings-bow.md
- README.md
- app/src/Form/Field.tsx
- app/src/Form/index.tsx
- src/types/index.ts
- src/types/react-cool-form.d.ts
- src/useForm.ts
- Refactor(useForm): rename `controller` to `field`
> refactor(useForm): rename "controller" to "field"

- .changeset/rude-moles-drive.md
- README.md
- app/src/Form/Field.tsx
- src/types/index.ts
- src/types/react-cool-form.d.ts
- src/useForm.ts
- Feat(useForm): add `controlled` option for `field` method
> Feat(useForm): add "controlled" option for "field" method

- .changeset/good-avocados-return.md
- .changeset/nine-shirts-behave.md
- README.md
- app/src/Form/index.tsx
- src/types/index.ts
- src/types/react-cool-form.d.ts
- src/useForm.ts
- Refactor(useForm): change `formRef` to `form`
> Refactor(useForm): change "formRef" to "form"

- .changeset/nine-shirts-behave.md
- README.md
- app/src/Form/index.tsx
- src/types/index.ts
- src/types/react-cool-form.d.ts
- src/useForm.ts
- Refactor(useForm): change `validate` to `field`
> Refactor(useForm): change "validate" to "field"

- .changeset/strong-wolves-judge.md
- README.md
- app/src/Form/Controller.tsx
- app/src/Form/index.tsx
- src/types/index.ts
- src/types/react-cool-form.d.ts
- src/useForm.ts
- Feat(useForm): add `parse` option for the field ref
- Fix(useForm): correct the behavior of `controller`
> Add "parse" option for field ref & correct the behavior of "controller"

- .changeset/few-steaks-punch.md
- src/useForm.ts
- Refactor(useForm): shorten code
> Refactor(useForm): shorten code

- .changeset/rotten-berries-wave.md
- package.json
- src/hooks/useState.ts
- yarn.lock
- Perf: use [dequal](https://github.com/lukeed/dequal) instead of [fast-deep-equal](https://github.com/epoberezkin/fast-deep-equal)
> Perf: use "dequal" instead of "fast-deep-equal"

- .changeset/smart-games-smile.md
- examples/basic/package.json
- src/types/index.ts
- src/types/react-cool-form.d.ts
- Fix(useForm): correct the `onChange` type of `controller`
> - Fix(useForm): correct the "onChange" type of "controller"

- website/babel.config.js
- website/docusaurus.config.js
- Chore(website): correct site URL
> Chore(website): correct site URL

- website/.gitignore
- Chore(website): refine .gitignore
> Chore(website): refine .gitignore

- website/.prettierignore
- website/package.json
- website/yarn.lock
- Chore(website): use [Prettier](https://prettier.io)
> Chore(website): use prettier

- .changeset/quiet-birds-try.md
- app/src/Playground/index.tsx
- src/useForm.ts
- Refactor(useForm): reduce unnecessary renders for the `getState` API
> Refactor(useForm): reduce unnecessary renders for "getState"

- .changeset/khaki-adults-tap.md
- README.md
- app/src/Playground/index.tsx
- docs/getting-started.md
- src/types/index.ts
- src/types/react-cool-form.d.ts
- src/useForm.ts
- Refactor(useForm): change `getState`'s option name from `filterUntouchedErrors` to `filterUntouchedError`
> refactor(useForm): change "getState" option name from "filterUntouchedErrors" to "filterUntouchedError"

- .changeset/sweet-melons-give.md
- app/src/Playground/index.tsx
- src/types/index.ts
- src/useForm.ts
- Fix(useForm): dynamic fields not working
> Fix(useForm): dynamic fields not working

- .changeset/sixty-bugs-wait.md
- app/src/Playground/index.tsx
- src/useForm.ts
- Fix(useForm): crash due to `undefined` field parsers
> Fix(useForm): crash due to undefined field parsers

- .changeset/polite-bugs-suffer.md
- src/types/index.ts
- src/types/react-cool-form.d.ts
- src/useForm.ts
- Feat(useForm): add `removeUnmountedField` config
> Feat(useForm): add "removeUnmountedField" config

- .changeset/light-shrimps-tan.md
- app/src/Playground/index.tsx
- src/useForm.ts
- src/utils/getTrueMap.ts
- src/utils/index.ts
- Perf(useForm): minimize the re-renders of `setValues`
> Perf(useForm): minimize the re-renders of "setValues"

- .changeset/red-kids-design.md
- app/src/Playground/index.tsx
- src/types/index.ts
- src/types/react-cool-form.d.ts
- src/useForm.ts
- Refactor(useForm): consist event's options
> Refactor(useForm): consist event's options

- .changeset/famous-radios-itch.md
- app/src/Playground/index.tsx
- src/types/index.ts
- src/types/react-cool-form.d.ts
- src/useForm.ts
- src/utils/isFieldElement.ts
- src/utils/setTrueValues.ts
- Feat(useForm): add a field-names callback for the option of `setValues`
> Feat(useForm): add field-names callback for the option of "setValues"

- .changeset/chatty-apricots-sparkle.md
- src/types/react-cool-form.d.ts
- Feat(types): export more types
> Feat(types): export more types

- .changeset/flat-turkeys-begin.md
- README.md
- app/src/Playground/index.tsx
- docs/getting-started/validation-guide.md
- src/types/index.ts
- src/types/react-cool-form.d.ts
- src/useForm.ts
- website/src/pages/index.js
- Feat(useForm): add `builtInValidationMode` option
> Feat(useForm): add "builtInValidationMode" option

- .changeset/dull-rings-jog.md
- app/src/Playground/index.tsx
- src/types/index.ts
- src/useForm.ts
- Fix(useForm): field updating laggy due to conditional fields
> Fix(useForm): field updating laggy due to conditional fields

- .changeset/orange-dots-run.md
- app/src/Playground/index.tsx
- src/hooks/useState.ts
- Perf(useForm): do not trigger re-rendering when imperatively setting the same values
> Perf(useForm): do not trigger re-rendering when imperatively setting the same values

- .changeset/ten-yaks-reflect.md
- app/src/Playground/index.tsx
- src/useForm.ts
- Fix(useForm): update `defaultValues` by `reset(nextValues)`
> Fix(useForm): update "defaultValues" by "reset(nextValues)"

- .changeset/cyan-onions-juggle.md
- app/src/Playground/index.tsx
- src/useForm.ts
- Fix(useForm): default value attribute not working when reset form
> Fix(useForm): default value attribute not working when reset form

- .changeset/wicked-zebras-rest.md
- src/types/react-cool-form.d.ts
- Refactor(types): adjust `.d.ts` file
> Refactor(types): adjust ".d.ts" file

- .changeset/nasty-chefs-eat.md
- app/src/Playground/index.tsx
- src/types/index.ts
- src/types/react-cool-form.d.ts
- src/useForm.ts
- Feat(useForm): change the `config` argument from required to optional
> Feat(useForm): change the "config" argument from required to optional

- .changeset/five-zoos-explode.md
- app/src/Playground/index.tsx
- src/useForm.ts
- Perf(useForm): avoid unnecessary re-renders when getting empty state
> Perf(useForm): avoid unnecessary re-renders when getting empty state

- .changeset/eight-cooks-swim.md
- src/types/index.ts
- src/types/react-cool-form.d.ts
- src/useForm.ts
- Refactor(types): change `Errors` to `FormErrors`
> Refactor(types): change "Errors" to "FormErrors"

- .changeset/gorgeous-bananas-sleep.md
- src/types/index.ts
- src/types/react-cool-form.d.ts
- Fix(useForm): correct the type of `setFieldValue`
> Fix(useForm): correct the type of "setFieldValue"

- .changeset/beige-mayflies-own.md
- src/utils/arrayToMap.ts
- src/utils/index.ts
- src/utils/set.ts
- src/utils/stringToPath.ts
- src/utils/unset.ts
- Fix(useForm): unset nested array value
> Fix(useForm): unset nested array value

- .changeset/angry-days-swim.md
- app/src/Playground/index.tsx
- src/useForm.ts
- Fix(useForm): skip warning for field with `data-rcf-ignore`
> Fix(useForm): skip warning for field with "data-rcf-ignore"

- .changeset/fast-parrots-repair.md
- src/utils/get.ts
- src/utils/stringToPath.ts
- Perf(utils): cache converted paths
> Perf(utils): cache converted paths

- .changeset/tender-roses-live.md
- app/src/Playground/index.tsx
- src/utils/stringToPath.ts
- Fix(useForm): can not clear field(s) due to the side-effect of caching paths
> Fix(useForm): can not clear field(s) due to the side-effect of caching paths

- .changeset/smart-fans-sniff.md
- app/src/Playground/index.tsx
- src/types/index.ts
- src/types/react-cool-form.d.ts
- src/useForm.ts
- Feat(useForm): adjust the `parse` and `onChange` APIs of the `controller` method
> Feat(useForm): adjust the "parse" and "onChange" APIs of the "controller" method

- .changeset/wise-games-speak.md
- docs/api-reference/use-form.md
- src/types/index.ts
- src/types/react-cool-form.d.ts
- src/useForm.ts
- Feat(useForm): rename `removeUnmountedField` to `shouldRemoveField`
> Feat(useForm): rename "removeUnmountedField" to "shouldRemoveField"

- .changeset/rotten-feet-drum.md
- docs/api-reference/use-form.md
- docs/getting-started/form-state.md
- src/hooks/__tests__/useState.ts
- src/hooks/useState.ts
- src/types/index.ts
- src/types/react-cool-form.d.ts
- src/useForm.ts
- Feat(useForm): rename `dirtyFields` state and option to `dirty`
> Feat(useForm): rename "dirtyFields" state and option to "dirty"

- .changeset/new-shirts-work.md
- app/src/Playground/index.tsx
- src/utils/cloneObject.ts
- Refactor(utils): `cloneObject` will not clone event object
> Refactor(utils): "cloneObject" will not clone event object

- .changeset/four-coats-deny.md
- src/hooks/__tests__/useState.ts
- src/hooks/useState.ts
- src/types/index.ts
- src/useForm.ts
- Perf(useState): delete used state when a field is removed
> Perf(useState): delete used state when a field is removed

- .changeset/khaki-apricots-bathe.md
- src/types/index.ts
- src/types/react-cool-form.d.ts
- src/useForm.ts
- Fix(useForm): pass all parameters back to the `onChange` handler of the `controller` API
> Fix(useForm): pass all parameters back to the "onChange" handler of the "controller" API

- .changeset/funny-lies-repair.md
- docs/api-reference/use-form.md
- docs/getting-started/validation-guide.md
- src/types/index.ts
- src/types/react-cool-form.d.ts
- src/useForm.ts
- tsconfig.json
- Remove `setValues` and `setErrors` methods
> Remove "setValues" and "setErrors" methods

- .changeset/ten-donuts-care.md
- app/src/Playground/index.tsx
- docs/api-reference/use-form.md
- docs/getting-started/3rd-party-ui-libraries.md
- docs/getting-started/complex-structures.md
- docs/getting-started/validation-guide.md
- src/types/index.ts
- src/types/react-cool-form.d.ts
- src/useForm.ts
- Rename `setFieldValue` to `setValue` & rename `setFieldError` to `setError`
> Rename "setFieldValue" to "setValue" & rename "setFieldError" to "setError"

- .changeset/hot-plants-thank.md
- app/src/Playground/index.tsx
- docs/api-reference/use-form.md
- docs/getting-started/3rd-party-ui-libraries.md
- src/types/index.ts
- src/types/react-cool-form.d.ts
- src/useForm.ts
- Feat(useForm): add `setTouched` method
> Feat(useForm): add "setTouched" method

- .changeset/violet-cups-guess.md
- app/src/Playground/index.tsx
- docs/api-reference/use-form.md
- docs/getting-started/validation-guide.md
- src/types/index.ts
- src/types/react-cool-form.d.ts
- src/useForm.ts
- src/utils/compact.ts
- src/utils/index.ts
- src/utils/stringToPath.ts
- Feat(useForm): combine `validateField` and `validateForm` into `runValidation`
> Feat(useForm): combine "validateField" and "validateForm" into "runValidation"

- .changeset/metal-hairs-judge.md
- app/src/Playground/index.tsx
- docs/api-reference/use-form.md
- src/types/react-cool-form.d.ts
- Refactor(type): require value for `setValue` and `setError`
> Refactor(type): require value for "setValue" and "setError"

- .changeset/olive-buses-poke.md
- src/useForm.ts
- src/utils/index.ts
- src/utils/setTrueValues.ts
- Refactor(utils): remove `setTrueValues` utility function
> Refactor(utils): remove "setTrueValues" utility function

- .changeset/grumpy-weeks-cheer.md
- src/utils/set.ts
- Fix(utils): set `array` type value correctly
> Fix(utils): set "array" type value correctly

- .changeset/khaki-trees-chew.md
- src/utils/set.ts
- Fix(utils): set `object` type value correctly
> Fix(utils): set "object" type value correctly

- .changeset/short-apes-shave.md
- src/utils/__tests__/set.ts
- src/utils/unset.ts
- Fix(utils): handle `unset` exception
> Fix(utils): handle "unset" exception

- .changeset/eight-tools-fail.md
- app/src/Playground/index.tsx
- src/utils/__tests__/unset.ts
- src/utils/unset.ts
- Fix(utils): unset all types of value
> Fix(utils): unset all types of value

- .changeset/cyan-pumas-cry.md
- src/utils/__tests__/unset.ts
- src/utils/unset.ts
- Fix(utils): correct the logic of `unset`
> Fix(utils): correct the logic of "unset"

- .changeset/few-ligers-sniff.md
- docs/api-reference/use-form.md
- src/types/index.ts
- src/types/react-cool-form.d.ts
- src/useForm.ts
- Feat(useForm): add `setDirty` method
> Feat(useForm): add "setDirty" method

- .changeset/large-suits-compare.md
- app/src/Playground/index.tsx
- docs/api-reference/use-form.md
- docs/getting-started/integration-an-existing-form.md
- src/types/index.ts
- src/types/react-cool-form.d.ts
- src/useForm.ts
- Feat(useForm): support non <form> element
> Feat(useForm): support non <form> element

- .changeset/polite-drinks-sniff.md
- src/hooks/useState.ts
- Fix(useState): trigger `debug` callback whenever form state changed
> Fix(useState): trigger "debug" callback whenever form state changed

- .changeset/khaki-seals-act.md
- src/types/react-cool-form.d.ts
> Refactor: refine types

- .changeset/eleven-parents-collect.md
- README.md
- docs/api-reference/use-form.md
- docs/getting-started/3rd-party-ui-libraries.md
- docs/getting-started/form-state.md
- docs/getting-started/form-submission.md
- docs/getting-started/getting-started.md
- docs/getting-started/integration-an-existing-form.md
- docs/getting-started/validation-guide.md
- src/types/index.ts
- src/types/react-cool-form.d.ts
- src/useForm.test.tsx
- src/useForm.ts
- website/src/pages/index.js
- Feat(useForm): add `select` method
> Feat(useForm): add "select" method

- .changeset/green-pandas-hang.md
- src/hooks/useState.test.ts
- src/hooks/useState.ts
- Refactor(useForm): do not trigger re-renders on reset if no selected state
> Refactor(useForm): do not trigger re-renders on reset if no selected state

- .changeset/angry-kids-rule.md
- src/hooks/useState.test.ts
- src/hooks/useState.ts
- src/useForm.test.tsx
- Fix(useForm): should call `debug` callback on every state changed
> Fix(useForm): should call "debug" callback on every state changed

- README.md
- app/src/Playground/index.tsx
- docs/api-reference/use-form-state.md
- docs/api-reference/use-form.md
- docs/getting-started/bundle-size-overview.md
- docs/getting-started/form-state.md
- examples/isolating-re-rendering/index.js
- examples/isolating-re-rendering/package.json
- examples/isolating-re-rendering/styles.scss
- src/hooks/useState.test.ts
- src/hooks/useState.ts
- src/index.ts
- src/shared.test.ts
- src/shared.ts
- src/types/index.ts
- src/types/react-cool-form.d.ts
- src/useForm.test.tsx
- src/useForm.ts
- src/useFormState.test.tsx
- src/useFormState.ts
- website/sidebars.js
- website/src/pages/index.js
- Feat: new `useFormState` hook
> Feat: new "useFormState" hook

- .changeset/dull-garlics-watch.md
- app/src/Playground/index.tsx
- docs/api-reference/use-form.md
- docs/getting-started/3rd-party-ui-libraries.md
- docs/getting-started/bundle-size-overview.md
- docs/getting-started/integration-an-existing-form.md
- src/useForm.test.tsx
- src/useForm.ts
- Feat(useForm): add `id` and `class` for the `excludeFields` option
> Feat(useForm): add "id" and "class" for the "excludeFields" option

- .changeset/angry-ducks-vanish.md
- src/useForm.test.tsx
- src/useForm.ts
- Fix(useForm): single checkbox input with valid `value` attribute, the value will be a string array
> Fix(useForm): single checkbox input with valid "value" attribute, the value will be a string array

- .changeset/red-mirrors-arrive.md
- app/src/Playground/index.tsx
- docs/api-reference/use-controlled.md
- docs/api-reference/use-form-methods.md
- docs/api-reference/use-form-state.md
- docs/api-reference/use-form.md
- docs/getting-started/3rd-party-ui-libraries.md
- docs/getting-started/bundle-size-overview.md
- docs/getting-started/form-state.md
- src/shared.test.ts
- src/shared.ts
- src/types/index.ts
- src/types/react-cool-form.d.ts
- src/useControlled.test.tsx
- src/useControlled.ts
- src/useForm.ts
- src/useFormMethods.test.tsx
- src/useFormMethods.ts
- src/useFormState.test.tsx
- src/useFormState.ts
- yarn.lock
- Feat: when only one form hook is using, we don't need the form id anymore
> Feat: when only one form hook is using, we don't need the form id anymore

- .changeset/sour-stingrays-tease.md
- docs/api-reference/utility-functions.md
- docs/getting-started/bundle-size-overview.md
- src/utils/unset.test.ts
- src/utils/unset.ts
- Feat(unset): remove the ancestry path of the unset property if needed
> Feat(unset): remove the ancestry path of the unset property if needed

- .changeset/curvy-dogs-pull.md
- app/src/Playground/index.tsx
- src/useForm.ts
- Fix(useForm): keep the value of a conditional field when `shouldRemoveField` option set to `false`
> Fix(useForm): keep the value of a conditional field when "shouldRemoveField" option set to "false"

- .changeset/odd-steaks-move.md
- src/utils/getIsDirty.test.ts
- src/utils/getIsDirty.ts
- Fix(useForm): `isDirty` not working with array type form values
> Fix(useForm): "isDirty" not working with array type form values

- .changeset/funny-humans-teach.md
- app/src/Playground/index.tsx
- package.json
- src/useFieldArray.ts
- yarn.lock
- Fix(useFieldArray): reset field value not working
> Fix(useFieldArray): reset field value not working

- .changeset/purple-spoons-try.md
- app/src/Playground/index.tsx
- src/useControlled.ts
- Fix(useControlled): controlled components not working with field-array
> Fix(useControlled): controlled components not working with field-array

- .changeset/four-meals-deliver.md
- app/src/Playground/index.tsx
- docs/api-reference/use-field-array.md
- docs/getting-started/arrays-and-lists.md
- docs/getting-started/bundle-size-overview.md
- src/types/index.ts
- src/useFieldArray.ts
- src/useForm.ts
- Feat(useFieldArray): better `fields` API for fixing the side-effect of [React Lists and Keys](https://reactjs.org/docs/lists-and-keys.html)
> Feat(useFieldArray): better "fields" API for fixing the side-effect of React keys and lists

- .changeset/cuddly-countries-enjoy.md
- src/useFieldArray.ts
- Fix(useFieldArray): fields not updated by helper methods
> Fix(useFieldArray): fields not updated by helper methods

- .changeset/gold-cows-hang.md
- app/src/Playground/index.tsx
- docs/api-reference/use-form-state.md
- docs/api-reference/use-form.md
- docs/getting-started/form-state.md
- src/types/index.ts
- src/types/react-cool-form.d.ts
- src/useForm.test.tsx
- src/useForm.ts
- src/useFormState.test.tsx
- tsconfig.json
- Feat: shortcut for getting form's values
> Feat: shortcut for getting form's values

- .changeset/tame-windows-jump.md
- app/src/Playground/index.tsx
- docs/api-reference/use-form.md
- docs/getting-started/arrays-and-lists.md
- docs/getting-started/bundle-size-overview.md
- src/useForm.ts
- Fix(useForm): `focus` method can accept delay = 0
> Fix(useForm): "focus" method can accept delay = 0

- .changeset/pretty-shoes-rhyme.md
- app/src/Playground/index.tsx
- bundlesize.config.json
- docs/api-reference/use-form.md
- docs/getting-started/bundle-size-overview.md
- docs/getting-started/form-state.md
- docs/getting-started/validation-guide.md
- src/types/index.ts
- src/types/react-cool-form.d.ts
- src/useForm.test.tsx
- src/useForm.ts
- Feat: add focus feature to `runValidation` API
> Feat: add focus feature to "runValidation" API

- .changeset/gorgeous-onions-kiss.md
- app/src/Playground/index.tsx
- src/hooks/useState.test.ts
- src/hooks/useState.ts
- src/types/index.ts
- src/useForm.test.tsx
- src/useForm.ts
- src/useFormState.ts
- Refactor: reduce bundle size
> Refactor: reduce bundle size

- .changeset/real-oranges-drive.md
- src/useControlled.ts
- Fix(useControlled): do not update default value when working with field-array
> Fix(useControlled): do not update default value when working with field-array

- scripts/rollup/cjsEntryFile.js
What changes are being made? (e.g. feature, bug, docs etc.)
This PR fixes a bug caused by two typos in `cjsEntryFile`.
Why are these changes necessary?
These typos were preventing the module from loading with the following error:
```
Error: Cannot find module './index.cjs.development.js.js'
.
.
.
code: 'MODULE_NOT_FOUND'
.
.
.
```
How were these changes implemented?
Have you done all of these things?
> Fix file format typos in cjsEntryFile

- .changeset/pretty-pots-travel.md
- app/src/Playground/index.tsx
- src/useForm.test.tsx
- src/useForm.ts
- src/useFormState.test.tsx
- Fix(useForm): reset form will cause `undefined` form values
> Fix(useForm): reset form will cause `undefined` form values

- .changeset/bright-poems-drive.md
- app/src/Playground/index.tsx
- docs/api-reference/use-form.md
- docs/getting-started/bundle-size-overview.md
- docs/getting-started/form-state.md
- src/types/index.ts
- src/types/react-cool-form.d.ts
- src/useControlled.test.tsx
- src/useControlled.ts
- src/useFieldArray.test.tsx
- src/useFieldArray.ts
- src/useForm.test.tsx
- src/useForm.ts
- Feat(useForm): new `removeOnUnmounted` option
> Feat(useForm): new `removeOnUnmounted` option

- .changeset/soft-plants-grow.md
- README.md
- app/src/Playground/index.tsx
- docs/api-reference/use-field-array.md
- docs/api-reference/use-form-state.md
- docs/api-reference/use-form.md
- docs/getting-started/3rd-party-ui-libraries.md
- docs/getting-started/accessibility.md
- docs/getting-started/arrays-and-lists.md
- docs/getting-started/bundle-size-overview.md
- docs/getting-started/form-state.md
- docs/getting-started/form-submission.md
- docs/getting-started/getting-started.md
- docs/getting-started/integration-an-existing-form.md
- docs/getting-started/validation-guide.md
- src/types/index.ts
- src/types/react-cool-form.d.ts
- src/useForm.test.tsx
- src/useForm.ts
- src/useFormMethods.test.tsx
- src/useFormMethods.ts
- src/useFormState.test.tsx
- Refactor(useForm): rename `mon` to `watchState` for better understanding
> Refactor(useForm): rename `mon` to `watchState` for better understanding

- .changeset/mighty-forks-speak.md
- .github/dependabot.yml
- README.md
- app/src/Playground/index.tsx
- docs/api-reference/use-field-array.md
- docs/api-reference/use-form-state.md
- docs/api-reference/use-form.md
- docs/getting-started/3rd-party-ui-libraries.md
- docs/getting-started/accessibility.md
- docs/getting-started/arrays-and-lists.md
- docs/getting-started/form-state.md
- docs/getting-started/form-submission.md
- docs/getting-started/getting-started.md
- docs/getting-started/integration-an-existing-form.md
- docs/getting-started/validation-guide.md
- src/types/index.ts
- src/types/react-cool-form.d.ts
- src/useForm.test.tsx
- src/useForm.ts
- src/useFormMethods.test.tsx
- src/useFormMethods.ts
- src/useFormState.test.tsx
- Refactor(useForm): rename `mon` method to `use`
> Refactor(useForm): rename `mon` method to `use`

- .changeset/soft-cooks-relate.md
- src/types/index.ts
- src/types/react-cool-form.d.ts
- src/useForm.ts
- Refactor(types): use overloads for the type of `useFormState` and the `field` method of `useForm`
> Refactor(types): use overloads for the type of `useFormState` and the `field` method of `useForm`

- .changeset/many-crews-remain.md
- package.json
- src/types/index.ts
- src/types/react-cool-form.d.ts
- yarn.lock
- Refactor(types): export more types
> Refactor(types): export more types

- .changeset/early-cats-eat.md
- README.md
- app/src/Playground/index.tsx
- bundlesize.config.json
- docs/api-reference/use-form.md
- docs/getting-started/3rd-party-ui-libraries.md
- docs/getting-started/bundle-size-overview.md
- docs/getting-started/form-submission.md
- src/types/index.ts
- src/types/react-cool-form.d.ts
- src/useForm.test.tsx
- src/useForm.ts
- Feat: add `shouldFocus` option for `runValidation` method
> Feat: add `shouldFocus` option for `runValidation` method

- .changeset/gold-melons-build.md
- src/useForm.test.tsx
- src/useForm.ts
- src/useFormState.test.tsx
- fix: `reset` method not working ( #695 )
> Fix: `reset` method not working
