.changeset/happy-singers-allow.md
rollup/config.js
rollup/createConfig.js

fix: correct UMD format

---

.changeset/slow-roses-arrive.md
examples/src/BasicForm/index.tsx
src/types/index.ts
src/types/react-cool-form.d.ts
src/useForm.ts

- Refactor(useForm): adjust the UX of defaultValues, reset(), and setValues()

Refactor(useForm): adjust the UX of defaultValues, reset(), and setValues()

---

.changeset/brave-beans-relax.md
package.json
src/runWithLowPriority.ts
src/types/global.d.ts
src/useForm.ts

- Refactor(useForm): use [requestIdleCallback](https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback) instead of [scheduler](https://www.npmjs.com/package/scheduler) to reduce bundle size

refactor(useForm): use requestIdleCallback instead of scheduler to reduce bundle size

---

.changeset/curvy-phones-occur.md
src/types/react-cool-form.d.ts

- Refactor(type): enhance the type of `controller`

- Refactor(type): enhance the type of "controller"

---

.changeset/angry-chefs-happen.md
examples/src/BasicForm/index.tsx
src/useForm.ts

- Feat(useForm): auto delete `undefined` value for `setFieldValue()`

Feat(useForm): auto delete undefined value for setFieldValue()

---

.changeset/eighty-balloons-stare.md
app/src/BasicForm/index.tsx
src/useForm.ts

- Feat(useForm): use `valueAsNumber` instead `parseFloat()` for converting data

feat(useForm): use "valueAsNumber" instead "parseFloat()" for converting data

---

.changeset/gorgeous-dodos-scream.md
README.md
src/types/index.ts
src/types/react-cool-form.d.ts
src/useForm.ts

- Fix(useForm): correct the logic of `controller` method

Fix(useForm): correct the logic of "controller" method

---

.changeset/tiny-kiwis-wave.md
app/src/Playground/index.tsx
src/useForm.ts

- Refactor(useForm): add warning for getting `values` state alone

Refactor(useForm): add warning for getting "values" state alone

---

.changeset/quiet-ducks-breathe.md
app/src/Playground/index.tsx
src/useForm.ts

- Fix(useForm): include non-form input elements into the set all touched of `submit`

Fix(useForm): include non-form input elements into the set all touched of "submit"

---

.changeset/light-pots-exist.md
app/src/Playground/index.tsx
src/types/index.ts
src/types/react-cool-form.d.ts
src/useForm.ts

- Refactor(useForm): use `formState` instead of the `getState` method for event handlers

Refactor(useForm): use "formState" instead of the "getState" method for event handlers

---

.changeset/small-forks-doubt.md
src/types/index.ts
src/types/react-cool-form.d.ts
src/useForm.ts

- Refactor(types): enhance the readability of type

Refactor(types): enhance the readability of type

---

.changeset/wet-terms-build.md
app/src/Playground/index.tsx
src/useForm.ts
src/utils/__tests__/isAsyncFunction.ts
src/utils/index.ts
src/utils/isAsyncFunction.ts

- Perf(useForm): do not trigger `isValidating` when running field-level validation

Perf(useForm): do not trigger "isValidating" when running field-level validation

---

.changeset/nice-turkeys-act.md
src/useForm.ts

- Fix(useForm): handle `getState` exception

Fix(useForm): handle "getState" exception

---

.changeset/popular-cougars-cover.md
app/src/Playground/index.tsx
src/useForm.ts

- Fix(useForm): do not count the `valid` key as an error when using built-in validation with state mode

Fix(useForm): do not count the "valid" key as an error when using built-in validation with state mode

---

.changeset/smart-lions-sip.md
docs/api-reference/use-form.md
src/types/index.ts
src/types/react-cool-form.d.ts
src/useForm.ts

- Feat(useForm): rename the option of `setValues` from `touchedFields` to `touched`

Feat(useForm): rename the option of "setValues" from "touchedFields" to "touched"

---

.changeset/tiny-chefs-poke.md
README.md
app/src/Playground/index.tsx
docs/api-reference/use-form.md
docs/getting-started/3rd-party-ui-libraries.md
docs/getting-started/complex-structures.md
docs/getting-started/form-state.md
docs/getting-started/form-submission.md
docs/getting-started/getting-started.md
docs/getting-started/validation-guide.md
src/types/index.ts
src/types/react-cool-form.d.ts
src/useForm.ts

- Breaking Change: Rename the option of `getState` from `filterUntouchedError` to `errorWithTouched`
- Breaking Change: The default of the `errorWithTouched` now is `false`

Breaking Change: Rename the option of "getState" from "filterUntouchedError" to "errorWithTouched" and change the default to "false"

---

.changeset/shaggy-cups-enjoy.md
src/useForm.ts

- Fix(useForm): should warn for missing field name

Fix(useForm): should warn for missing field name

---

.changeset/loud-socks-glow.md
src/useForm.ts

- Fix(useForm): prevent errors from calling `e.preventDefault()` and `e.stopPropagation()` when using `submit` or `reset` methods

Fix(useForm): prevent errors from calling "e.preventDefault()" and "e.stopPropagation()" when using "submit" or "reset" methods

---

.changeset/purple-hats-appear.md
src/useForm.ts

- Fix(useForm): `dirty` and `isDirty` state not work correctly with reference type values

Fix(useForm): "dirty" and "isDirty" state not work correctly with reference type values

---

.changeset/giant-gorillas-smoke.md
.changeset/nervous-walls-sniff.md
README.md
docs/api-reference/use-form-state.md
docs/api-reference/use-form.md
docs/getting-started/3rd-party-ui-libraries.md
docs/getting-started/form-state.md
docs/getting-started/form-submission.md
docs/getting-started/getting-started.md
docs/getting-started/integration-an-existing-form.md
docs/getting-started/typescript-support.md
docs/getting-started/validation-guide.md
src/types/index.ts
src/types/react-cool-form.d.ts
src/useForm.test.tsx
src/useForm.ts
src/useFormMethods.test.tsx
src/useFormMethods.ts
src/useFormState.test.tsx

- Rename `select` method to `mon` (a.k.a monitor)

Rename "select" method to "mon" (a.k.a monitor)

---

.changeset/lucky-phones-melt.md
src/useForm.test.tsx
src/useForm.ts

- Fix(useForm): throw multiple warning when getting form values with `mon` method

Fix(useForm): throw multiple warning when getting form values with "mon" method

---

.changeset/hungry-pants-play.md
src/useForm.test.tsx
src/useForm.ts

- Fix(useForm): when running field-level validation with nested field(s), the last field will overrides the error results

Fix(useForm): when running field-level validation with nested field(s), the last field will overrides the error results

---

.changeset/big-radios-sin.md
app/src/Playground/index.tsx
src/useForm.ts
src/useFormState.test.tsx
src/utils/filterErrors.test.ts

- Fix(useFormState): `errorWithTouched` option not works in some cases

Fix(useFormState): "errorWithTouched" option not works in some cases

---

.changeset/tame-avocados-yawn.md
app/src/Playground/index.tsx
src/useForm.test.tsx
src/useForm.ts

- Fix(useForm): do not warn missing name when excluding a field via `data-rcf-exclude`

Fix(useForm): do not warn missing name when excluding a field via `data-rcf-exclude`

---

.changeset/cold-dolphins-sneeze.md
app/src/Playground/index.tsx
docs/api-reference/use-form.md
docs/getting-started/validation-guide.md
src/types/index.ts
src/types/react-cool-form.d.ts
src/useForm.test.tsx
src/useForm.ts

- Refactor(useForm): deprecate the `shouldFocus` parameter of `runValidation` API

Refactor(useForm): deprecate the `shouldFocus` parameter of `runValidation` API

---

.changeset/weak-dragons-act.md
src/useForm.ts

- Fix(useForm): when dynamically hide a field `getState("foo")` will get the default value

Fix(useForm): when dynamically hide a field `getState("foo")` will get the default value

---

.changeset/cyan-bees-pretend.md
src/useControlled.ts

- Fix(useControlled): value not updated when working with conditional fields and setting default value from `defaultValue` option

Fix(useControlled): value not updated when working with conditional fields and setting default value from `defaultValue` option

---

.changeset/grumpy-moons-design.md
docs/api-reference/use-form.md
src/hooks/useState.test.ts
src/hooks/useState.ts
src/types/index.ts
src/types/react-cool-form.d.ts
src/useForm.test.tsx
src/useForm.ts

- Refactor(useForm): rename `debug` event to `onStateChange`

Refactor(useForm): rename `debug` event to `onStateChange`

---

.changeset/red-mice-clean.md
docs/getting-started/bundle-size-overview.md
docs/getting-started/form-state.md
src/useForm.test.tsx
src/useForm.ts

- Refactor(form-state): reset `isSubmitted` state when the user attempts to submit the form

Refactor(form-state): reset `isSubmitted` state when the user attempts to submit the form

---

.changeset/moody-peaches-protect.md
docs/api-reference/use-form.md
src/types/index.ts
src/types/react-cool-form.d.ts
src/useControlled.test.tsx
src/useFieldArray.test.tsx
src/useForm.test.tsx
src/useForm.ts

- Refactor(useForm): turn the 3rd parameter of `setTouched` to an option for the purpose of API consistency

Refactor(useForm): turn the 3rd parameter of `setTouched` to an option for the purpose of API consistency

---

.changeset/empty-tools-complain.md
src/types/index.ts
src/types/react-cool-form.d.ts

- refactor(types): use `RefObject` as the type of `form` method

refactor(types): use `RefObject` as the type of `form` method
